CREATE TABLE IF NOT EXISTS recorded_positions (
    id BIGSERIAL PRIMARY KEY,
    joint_1 DOUBLE PRECISION NOT NULL,
    joint_2 DOUBLE PRECISION NOT NULL,
    joint_3 DOUBLE PRECISION NOT NULL,
    joint_4 DOUBLE PRECISION NOT NULL,
    joint_5 DOUBLE PRECISION NOT NULL,
    joint_6 DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);